---------------------------------------------------------------------------------------------------
--COSTUMER TABLE
---------------------------------------------------------------------------------------------------
CREATE TABLE CUSTOMER (
    NAME VARCHAR(30) NOT NULL,
    PHONENO VARCHAR(11) PRIMARY KEY,
    ADDRESS VARCHAR(100) NOT NULL
);

/
---------------------------------------------------------------------------------------------------
--MACHINE TABLE
---------------------------------------------------------------------------------------------------
CREATE TABLE MACHINE(
    MACHINEID NUMBER PRIMARY KEY,
    PARENTMACHINEID NUMBER,
    MAKE VARCHAR(30) NOT NULL,
    MODEL VARCHAR(30) NOT NULL,
    YEAR DATE NOT NULL,
    TYPE CHAR(1) NOT NULL,
    "size" NUMBER,
    CONSTRAINTS FK_PARENTMACHINE FOREIGN KEY (PARENTMACHINEID) REFERENCES MACHINE(MACHINEID) ON DELETE SET NULL,
    CONSTRAINT CK_PARENT_TYPE Check(PARENTMACHINEID is Not null and type = 'M' or PARENTMACHINEID is null)
);

/
---------------------------------------------------------------------------------------------------
--SERVICE CONTRACTS TABLE
---------------------------------------------------------------------------------------------------
CREATE TABLE SERVICE_CONTRACT(
    CONTRACTID NUMBER,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    ACTIVE NUMBER(1, 0) NOT NULL,
    PHONENO VARCHAR(11),
    PRIMARY KEY(CONTRACTID),
    CONSTRAINTS FK_CUSTOMER FOREIGN KEY (PHONENO) REFERENCES CUSTOMER (PHONENO),
    CONSTRAINT CK_DATES CHECK(ENDDATE > STARTDATE)
);

/
---------------------------------------------------------------------------------------------------
--SERVICE ITEMS TABLE
---------------------------------------------------------------------------------------------------
CREATE TABLE SERVICE_ITEM ( 
    CONTRACTID NUMBER NOT NULL, 
    MACHINEID NUMBER NOT NULL, 
    SERVICETYPE VARCHAR(1) DEFAULT 'H' NOT NULL, 
    FEE NUMBER, PRIMARY KEY (SERVICETYPE, CONTRACTID, MACHINEID), 
    CONSTRAINT FK_SERVICEITEM_SERVICECONTRACT FOREIGN KEY (CONTRACTID) REFERENCES SERVICE_CONTRACT(CONTRACTID) ON DELETE CASCADE, 
    CONSTRAINT FK_SERVICEITEM_MACHINE FOREIGN KEY (MACHINEID) REFERENCES MACHINE(MACHINEID),
    CONSTRAINT CK_SERVICETYPE CHECK(SERVICETYPE IN ('H','S')));

/
---------------------------------------------------------------------------------------------------
--DELETED CONTRACTS TABLE
---------------------------------------------------------------------------------------------------
CREATE TABLE DELETED_SERVICE_CONTRACT (
    CONTRACTID NUMBER NOT NULL PRIMARY KEY,
    DATEDELETED DATE NOT NULL
);

/

CREATE OR REPLACE TRIGGER TR_DELETE_CONTRACT AFTER
    DELETE ON SERVICE_CONTRACT FOR EACH ROW
BEGIN
    INSERT INTO DELETED_SERVICE_CONTRACT VALUES(
        :OLD.CONTRACTID,
        CURRENT_DATE
    );
END;

/
---------------------------------------------------------------------------------------------------
--REPAIR JOBS TABLE
---------------------------------------------------------------------------------------------------
create Table REPAIR_JOB (
    repairJobId number GENERATED BY DEFAULT ON NULL AS IDENTITY ,
    phoneNo varchar(11) not null,
    startDate Date not null,
    endDate Date,
    Constraint PK_repairJob Primary Key(repairJobId),
    Constraint Fk_repairJob_customer Foreign Key (phoneNo) references Customer(phoneNo))
  
/  
---------------------------------------------------------------------------------------------------
--REPAIR JOBS ITEM
---------------------------------------------------------------------------------------------------
CREATE TABLE REPAIR_ITEM (
    REPAIRITEMID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    REPAIRJOBID NUMBER NOT NULL,
    MACHINEID NUMBER NOT NULL,
    SERVICEFEE NUMBER,
    CONSTRAINT PK_REPAIRITEM PRIMARY KEY(REPAIRITEMID),
    CONSTRAINT FK_REPAIRITEM_REPAIRJOB FOREIGN KEY (REPAIRJOBID) REFERENCES REPAIR_JOB(REPAIRJOBID),
    CONSTRAINT FK_REPAIRITEM_MACHINE FOREIGN KEY (MACHINEID) REFERENCES MACHINE(MACHINEID)
)

/
---------------------------------------------------------------------------------------------------
--REPAIR JOBS ITEM
---------------------------------------------------------------------------------------------------
CREATE TABLE PARTS (
    PARTID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
)

/
---------------------------------------------------------------------------------------------------
--REPAIR PARTS 
---------------------------------------------------------------------------------------------------
CREATE TABLE REPAIR_PARTS (
    PARTID NUMBER NOT NULL,
    REPAIRITEMID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    CONSTRAINT PK_REPAIR_PARTS PRIMARY KEY (PARTID, REPAIRITEMID),
    CONSTRAINT FK_REPAIRPART_PART FOREIGN KEY(PARTID) REFERENCES PARTS(PARTID),
    CONSTRAINT FK_REPAIRPART_REPAIRITEM FOREIGN KEY(REPAIRITEMID) REFERENCES REPAIR_ITEM(REPAIRITEMID)
)